AWSTemplateFormatVersion: '2010-09-09'
Description: Definición de políticas de IAM

Resources:
  PolicyClientesIntegr:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "PolicyClientesIntegr"
      Roles:
        - !ImportValue RolClientesIntegrArn
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances*"
            Resource: "*"

  PolicyClientesIntcus:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "PolicyClientesIntcus"
      Roles:
        - !ImportValue RolClientesIntcusArn
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances*"
            Resource: "*"

Outputs:
  PolicyClientesIntegrArn:
    Description: "ARN de la política Clientes Integr"
    Value: !Ref PolicyClientesIntegr

  PolicyClientesIntcusArn:
    Description: "ARN de la política Clientes Intcus"
    Value: !Ref PolicyClientesIntcus