name: Deploy Cluster

on:
  push:
    branches:
      - development

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_CFN }}
        role-session-name: GitHubActionsAWSAccess

    - name: Stack de CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: SA-Integr
        template: cloudformation/integr.yaml
        capabilities: CAPABILITY_IAM
        no-fail-on-empty-changeset: '1'

